# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='empresa',
        ),
        migrations.AddField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 1, 2, 33, 54, 833414)),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.Cliente'),
        ),
    ]
