# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='acessorios',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 8, 1, 23, 7, 234915), null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_aprovacao',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_envio_orcamento',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_liberacao',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='executante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='num_nf_devolucao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='num_nf_entrada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='num_nf_servico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='num_nf_vendas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='num_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='responsavel_preenchimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
