# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0002_auto_20170608_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 21, 13, 31, 22, 836116), null=True),
        ),
    ]
