# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0002_auto_20170601_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordem',
            name='cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 1, 2, 35, 51, 40657)),
        ),
    ]
