# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0003_auto_20170601_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 1, 2, 38, 46, 757290), null=True),
        ),
    ]
