# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0004_auto_20170601_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 6, 13, 20, 27, 611754), null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_aprovacao',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_envio_orcamento',
            field=models.CharField(max_length=14),
        ),
    ]
